import { Router, type IRouter } from "express";
import { and, desc, eq, isNotNull } from "drizzle-orm";
import PDFDocument from "pdfkit";
import { db, tasksTable, agentsTable, propertiesTable } from "@workspace/db";

const router: IRouter = Router();

router.get("/reports", async (req, res): Promise<void> => {
  const propertyId = req.query.propertyId ? Number(req.query.propertyId) : undefined;

  const conditions = [isNotNull(tasksTable.output)];
  if (propertyId) {
    conditions.push(eq(tasksTable.propertyId, propertyId));
  }

  const reports = await db
    .select({
      id: tasksTable.id,
      title: tasksTable.title,
      output: tasksTable.output,
      createdAt: tasksTable.createdAt,
      agentId: tasksTable.agentId,
      propertyId: tasksTable.propertyId,
      agentName: agentsTable.name,
      agentIcon: agentsTable.icon,
      agentColor: agentsTable.color,
      propertyName: propertiesTable.name,
    })
    .from(tasksTable)
    .innerJoin(agentsTable, eq(tasksTable.agentId, agentsTable.id))
    .innerJoin(propertiesTable, eq(tasksTable.propertyId, propertiesTable.id))
    .where(and(...conditions))
    .orderBy(desc(tasksTable.createdAt))
    .limit(100);

  res.json(reports.map((r) => ({
    id: r.id,
    title: r.title,
    agentId: r.agentId,
    agentName: r.agentName,
    agentIcon: r.agentIcon,
    agentColor: r.agentColor,
    propertyId: r.propertyId,
    propertyName: r.propertyName,
    outputSnippet: r.output ? r.output.substring(0, 200) : null,
    createdAt: r.createdAt?.toISOString() ?? null,
  })));
});

router.get("/reports/:id", async (req, res): Promise<void> => {
  const id = Number(req.params.id);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid report id" });
    return;
  }

  const [report] = await db
    .select({
      id: tasksTable.id,
      title: tasksTable.title,
      output: tasksTable.output,
      createdAt: tasksTable.createdAt,
      agentId: tasksTable.agentId,
      propertyId: tasksTable.propertyId,
      agentName: agentsTable.name,
      agentIcon: agentsTable.icon,
      agentColor: agentsTable.color,
      propertyName: propertiesTable.name,
    })
    .from(tasksTable)
    .innerJoin(agentsTable, eq(tasksTable.agentId, agentsTable.id))
    .innerJoin(propertiesTable, eq(tasksTable.propertyId, propertiesTable.id))
    .where(and(eq(tasksTable.id, id), isNotNull(tasksTable.output)));

  if (!report) {
    res.status(404).json({ error: "Report not found" });
    return;
  }

  res.json({
    id: report.id,
    title: report.title,
    agentId: report.agentId,
    agentName: report.agentName,
    agentIcon: report.agentIcon,
    agentColor: report.agentColor,
    propertyId: report.propertyId,
    propertyName: report.propertyName,
    output: report.output,
    createdAt: report.createdAt?.toISOString() ?? null,
  });
});

router.get("/reports/:id/download.pdf", async (req, res): Promise<void> => {
  const id = Number(req.params.id);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid report id" });
    return;
  }

  const [report] = await db
    .select({
      id: tasksTable.id,
      title: tasksTable.title,
      output: tasksTable.output,
      createdAt: tasksTable.createdAt,
      agentName: agentsTable.name,
      agentIcon: agentsTable.icon,
      propertyName: propertiesTable.name,
    })
    .from(tasksTable)
    .innerJoin(agentsTable, eq(tasksTable.agentId, agentsTable.id))
    .innerJoin(propertiesTable, eq(tasksTable.propertyId, propertiesTable.id))
    .where(and(eq(tasksTable.id, id), isNotNull(tasksTable.output)));

  if (!report) {
    res.status(404).json({ error: "Report not found" });
    return;
  }

  const filename = `report_${id}_${(report.title ?? "report").replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf`;
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);

  const doc = new PDFDocument({ margin: 50, size: "A4" });
  doc.pipe(res);

  const accent = "#4f46e5";
  const primary = "#1a1a2e";
  const gray = "#6b7280";

  doc.fillColor(accent).fontSize(20).font("Helvetica-Bold").text("Marketing Report", { align: "center" });
  doc.moveDown(0.3);
  doc.fillColor(primary).fontSize(14).font("Helvetica").text(report.propertyName, { align: "center" });
  doc.moveDown(0.2);
  doc.fillColor(gray).fontSize(10).text(report.title ?? "", { align: "center" });
  doc.moveDown(0.2);
  if (report.createdAt) {
    doc.fillColor(gray).text(`Generated by ${report.agentName} ${report.agentIcon ?? ""}  ·  ${new Date(report.createdAt).toLocaleString()}`, { align: "center" });
  }
  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e5e7eb").stroke();
  doc.moveDown(1);

  doc.fillColor(primary).fontSize(10).font("Helvetica");

  const lines = (report.output ?? "").split("\n");
  for (const line of lines) {
    if (line.startsWith("# ")) {
      doc.moveDown(0.4);
      doc.fillColor(accent).fontSize(14).font("Helvetica-Bold").text(line.replace(/^# /, ""));
      doc.fillColor(primary).fontSize(10).font("Helvetica");
    } else if (line.startsWith("## ")) {
      doc.moveDown(0.3);
      doc.fillColor("#374151").fontSize(12).font("Helvetica-Bold").text(line.replace(/^## /, ""));
      doc.fillColor(primary).fontSize(10).font("Helvetica");
    } else if (line.startsWith("### ")) {
      doc.moveDown(0.2);
      doc.fillColor("#374151").fontSize(11).font("Helvetica-Bold").text(line.replace(/^### /, ""));
      doc.fillColor(primary).fontSize(10).font("Helvetica");
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      doc.text(`  • ${line.replace(/^[-*] /, "")}`, { indent: 10 });
    } else if (line.trim() === "") {
      doc.moveDown(0.3);
    } else {
      doc.text(line);
    }
  }

  doc.end();
});

router.get("/reports/:id/download.csv", async (req, res): Promise<void> => {
  const id = Number(req.params.id);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid report id" });
    return;
  }

  const [report] = await db
    .select({
      id: tasksTable.id,
      title: tasksTable.title,
      output: tasksTable.output,
      createdAt: tasksTable.createdAt,
      agentName: agentsTable.name,
      propertyName: propertiesTable.name,
    })
    .from(tasksTable)
    .innerJoin(agentsTable, eq(tasksTable.agentId, agentsTable.id))
    .innerJoin(propertiesTable, eq(tasksTable.propertyId, propertiesTable.id))
    .where(and(eq(tasksTable.id, id), isNotNull(tasksTable.output)));

  if (!report) {
    res.status(404).json({ error: "Report not found" });
    return;
  }

  const filename = `report_${id}_${(report.title ?? "report").replace(/[^a-z0-9]/gi, "_").toLowerCase()}.csv`;
  res.setHeader("Content-Type", "text/csv");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);

  const escape = (val: string) => `"${val.replace(/"/g, '""')}"`;

  const rows: string[] = [
    ["Field", "Value"].map(escape).join(","),
    ["Report ID", String(report.id)].map(escape).join(","),
    ["Title", report.title ?? ""].map(escape).join(","),
    ["Agent", report.agentName].map(escape).join(","),
    ["Property", report.propertyName].map(escape).join(","),
    ["Generated At", report.createdAt?.toISOString() ?? ""].map(escape).join(","),
    [],
    ["Section", "Content"].map(escape).join(","),
  ].map((r) => (Array.isArray(r) ? "" : r));

  const output = report.output ?? "";
  let currentSection = "Full Report";
  const sectionRows: string[] = [];

  for (const line of output.split("\n")) {
    if (line.startsWith("# ") || line.startsWith("## ") || line.startsWith("### ")) {
      currentSection = line.replace(/^#{1,3} /, "");
    } else if (line.trim() !== "") {
      sectionRows.push([currentSection, line].map(escape).join(","));
    }
  }

  const csv = [...rows, ...sectionRows].join("\n");
  res.send(csv);
});

export default router;
