import { useState } from "react";
import { useListReports, useGetReport, useListProperties, getGetReportQueryKey } from "@workspace/api-client-react";
import { format } from "date-fns";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { FileText, Download, Eye } from "lucide-react";

export default function Reports() {
  const [propertyFilter, setPropertyFilter] = useState<number | undefined>();
  const [selectedReportId, setSelectedReportId] = useState<number | null>(null);

  const { data: properties = [] } = useListProperties();
  const { data: reports = [], isLoading } = useListReports(
    propertyFilter ? { propertyId: propertyFilter } : {}
  );
  const { data: reportDetail } = useGetReport(selectedReportId ?? 0, {
    query: { enabled: selectedReportId != null, queryKey: getGetReportQueryKey(selectedReportId ?? 0) },
  });

  const downloadPdf = (id: number) => {
    window.open(`/api/reports/${id}/download.pdf`, "_blank");
  };

  const downloadReportCsv = (id: number) => {
    window.open(`/api/reports/${id}/download.csv`, "_blank");
  };

  const downloadAnalyticsCsv = (propertyId: number, range: string) => {
    window.open(`/api/properties/${propertyId}/analytics-data.csv?dateRange=${range}`, "_blank");
  };

  const downloadAnalyticsPdf = (propertyId: number, range: string) => {
    window.open(`/api/properties/${propertyId}/analytics-data.pdf?dateRange=${range}`, "_blank");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Reports</h1>
          <p className="text-muted-foreground mt-1">View and download agent-generated reports and analytics exports</p>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Reports</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{reports.length}</div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Analytics Exports</CardTitle>
              <CardDescription>Download raw analytics data for any property</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {properties.length === 0 ? (
            <p className="text-sm text-muted-foreground">No properties configured.</p>
          ) : (
            <div className="space-y-3">
              {properties.map((p) => (
                <div key={p.id} className="flex items-center justify-between py-2 border-b border-border last:border-0">
                  <div className="font-medium text-sm">{p.name}</div>
                  <div className="flex items-center gap-2 flex-wrap justify-end">
                    {(["7days", "30days", "90days"] as const).map((range) => (
                      <div key={range} className="flex gap-1">
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-7 text-xs gap-1"
                          onClick={() => downloadAnalyticsCsv(p.id, range)}
                        >
                          <Download className="h-3 w-3" />
                          {range} CSV
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-7 text-xs gap-1"
                          onClick={() => downloadAnalyticsPdf(p.id, range)}
                        >
                          <Download className="h-3 w-3" />
                          {range} PDF
                        </Button>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Agent Reports</CardTitle>
              <CardDescription>All reports generated by AI agents across properties</CardDescription>
            </div>
            <Select
              value={propertyFilter ? String(propertyFilter) : "all"}
              onValueChange={(v) => setPropertyFilter(v === "all" ? undefined : Number(v))}
            >
              <SelectTrigger className="w-44">
                <SelectValue placeholder="All properties" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All properties</SelectItem>
                {properties.map((p) => (
                  <SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-sm text-muted-foreground">Loading reports…</p>
          ) : reports.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <FileText className="h-10 w-10 mx-auto mb-3 opacity-30" />
              <p className="text-sm">No reports yet. Run an agent task to generate reports.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {reports.map((report) => (
                <div
                  key={report.id}
                  className="flex items-start gap-3 p-3 rounded-lg border border-border hover:bg-muted/50 transition-colors"
                >
                  <div
                    className="w-8 h-8 rounded flex items-center justify-center text-white text-sm shrink-0 mt-0.5"
                    style={{ backgroundColor: report.agentColor ?? "#6b7280" }}
                  >
                    {report.agentIcon}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-sm font-medium leading-snug">{report.title ?? "Untitled Report"}</p>
                      <div className="flex items-center gap-1 shrink-0">
                        <Button
                          size="sm"
                          variant="ghost"
                          className="h-7 w-7 p-0"
                          title="View report"
                          onClick={() => setSelectedReportId(report.id)}
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-7 px-2 text-xs gap-1"
                          title="Download CSV"
                          onClick={() => downloadReportCsv(report.id)}
                        >
                          <Download className="h-3 w-3" />
                          CSV
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-7 px-2 text-xs gap-1"
                          title="Download PDF"
                          onClick={() => downloadPdf(report.id)}
                        >
                          <Download className="h-3 w-3" />
                          PDF
                        </Button>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 mt-1">
                      <Badge variant="secondary" className="text-xs">{report.agentName}</Badge>
                      <span className="text-xs text-muted-foreground">{report.propertyName}</span>
                      {report.createdAt && (
                        <span className="text-xs text-muted-foreground">
                          · {format(new Date(report.createdAt), "MMM d, yyyy")}
                        </span>
                      )}
                    </div>
                    {report.outputSnippet && (
                      <p className="text-xs text-muted-foreground mt-1.5 line-clamp-2">
                        {report.outputSnippet}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      <Dialog open={selectedReportId != null} onOpenChange={(open) => !open && setSelectedReportId(null)}>
        <DialogContent className="max-w-3xl max-h-[80vh] flex flex-col">
          <DialogHeader>
            <DialogTitle>{reportDetail?.title ?? "Report"}</DialogTitle>
          </DialogHeader>
          <div className="flex items-center gap-2 py-2 border-b border-border shrink-0">
            <div
              className="w-6 h-6 rounded flex items-center justify-center text-white text-xs"
              style={{ backgroundColor: reportDetail?.agentColor ?? "#6b7280" }}
            >
              {reportDetail?.agentIcon}
            </div>
            <span className="text-sm text-muted-foreground">
              {reportDetail?.agentName} · {reportDetail?.propertyName}
            </span>
            {reportDetail?.createdAt && (
              <span className="text-xs text-muted-foreground ml-auto">
                {format(new Date(reportDetail.createdAt), "MMM d, yyyy h:mm a")}
              </span>
            )}
            <Button
              size="sm"
              variant="outline"
              className="gap-1 ml-2"
              onClick={() => selectedReportId && downloadPdf(selectedReportId)}
            >
              <Download className="h-3.5 w-3.5" />
              PDF
            </Button>
          </div>
          <div className="overflow-y-auto flex-1 mt-2">
            <pre className="text-sm whitespace-pre-wrap font-sans leading-relaxed text-foreground">
              {reportDetail?.output ?? "Loading…"}
            </pre>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
